apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

resources:
- ..\ClusterRole\kube-state-metrics.yaml
- ..\ClusterRoleBinding\kube-state-metrics.yaml
- ..\ServiceAccount\kube-state-metrics.yaml
- ..\Deployments\kube-state-metrics.yaml
- ..\Services\kube-state-metrics.yaml