[project]
name = "fiap-api-loadtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faker>=33.1.0",
    "locust>=2.32.4",
]
