apiVersion: v1
kind: Service
metadata:
  name: criar-contato-service
  namespace: fiap-contacts
spec: 
  selector:
    app: criar-contato
  ports:
    - protocol: TCP
      port: 5131
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: consultar-contato-service
  namespace: fiap-contacts
spec: 
  selector:
    app: consultar-contato
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: consultar-contato-service-ext
  namespace: fiap-contacts
spec: 
  selector:
    app: consultar-contato
  ports:
    - protocol: TCP
      port: 5132
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: alterar-contato-service
  namespace: fiap-contacts
spec: 
  selector:
    app: alterar-contato
  ports:
    - protocol: TCP
      port: 5133
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: excluir-contato-service
  namespace: fiap-contacts
spec: 
  selector:
    app: excluir-contato
  ports:
    - protocol: TCP
      port: 5134
      targetPort: 8080
  type: LoadBalancer