apiVersion: v1
kind: Service
metadata:
  name: otel-collector-service
  namespace: fiap-contacts
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: prometheus-metrics
    port: 8889
    targetPort: 8889
  type: ClusterIP