apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: fiap-contacts
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      prometheus:
        config:
          scrape_configs:
            - job_name: 'dotnet-services'
              scrape_interval: 15s
              static_configs:
                - targets: 
                  - 'criar-contato-service:5131'
                  - 'consultar-contato-service:5132'
                  - 'alterar-contato-service:5133'
                  - 'excluir-contato-service:5134'

    processors:
      batch:

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [prometheus, logging]