apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: fiap-contacts
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
